updated mgitstatus

diff --git a/files/mgitstatus b/files/mgitstatus
--- a/files/mgitstatus
+++ b/files/mgitstatus
@@ -1,26 +1,32 @@
 #!/bin/sh
+# File managed by Ansible
+#
+# https://github.com/fboender/multi-git-status
+#
 
 # MIT license
 
-VERSION="2.0"
+VERSION="2.2"
 DEBUG=0
 
 usage () {
     cat << EOF >&2
     
-Usage: $0 [--version] [-w] [-e] [-f] [--no-X] [-d/--depth=2] [DIR [DIR]...]
+Usage: $0 [--version] [-w] [-e] [-f] [--throttle SEC] [-c] [-d/--depth=2] [--flatten] [--no-X] [DIR [DIR]...]
 
 mgitstatus shows uncommitted, untracked and unpushed changes in multiple Git
-repositories.  By default, mgitstatus scans two directories deep. This can be
+repositories. By default, mgitstatus scans two directories deep. This can be
 changed with the -d (--depth) option.  If DEPTH is 0, the scan is infinitely
 deep.
 
-  --version      Show version
-  -w             Warn about dirs that are not Git repositories
-  -e             Exclude repos that are 'ok'
-  -f             Do a 'git fetch' on each repo (slow for many repos)
-  -c             Force color output (preserve colors when using pipes)
-  -d, --depth=2  Scan this many directories deep
+  --version        Show version
+  -w               Warn about dirs that are not Git repositories
+  -e               Exclude repos that are 'ok'
+  -f               Do a 'git fetch' on each repo (slow for many repos)
+  --throttle SEC   Wait SEC seconds between each 'git fetch' (-f option)
+  -c               Force color output (preserve colors when using pipes)
+  -d, --depth=2    Scan this many directories deep
+  --flatten        Show only one status per line
 
 You can limit output with the following options:
 
@@ -30,6 +36,7 @@ You can limit output with the following options:
   --no-uncommitted
   --no-untracked
   --no-stashes
+  --no-ok          (same as -e)
     
 EOF
 }
@@ -39,12 +46,14 @@ WARN_NOT_REPO=0
 EXCLUDE_OK=0
 DO_FETCH=0
 FORCE_COLOR=0
+FLATTEN=0
 NO_PUSH=0
 NO_PULL=0
 NO_UPSTREAM=0
 NO_UNCOMMITTED=0
 NO_UNTRACKED=0
 NO_STASHES=0
+THROTTLE=0
 DEPTH=2
 
 while [ -n "$1" ]; do
@@ -71,6 +80,9 @@ while [ -n "$1" ]; do
     if [ "$1" = "-c" ]; then
         FORCE_COLOR=1
     fi
+    if [ "$1" = "--flatten" ]; then
+        FLATTEN=1
+    fi
     if [ "$1" = "--no-push" ]; then
         NO_PUSH=1
     fi
@@ -89,6 +101,21 @@ while [ -n "$1" ]; do
     if [ "$1" = "--no-stashes" ]; then
         NO_STASHES=1
     fi
+    if [ "$1" = "--no-ok" ]; then
+        # Same as -e, but -e violates the principle of least astonishment.
+        EXCLUDE_OK=1
+    fi
+    if [ "$1" = "--throttle" ]; then
+        THROTTLE="$2"
+        echo "$THROTTLE" | grep -E "^[0-9]+$" > /dev/null 2>&1
+        IS_NUM="$?"
+        if [ "$IS_NUM" -ne 0 ]; then
+            echo "Invalid value for 'throttle' (must be a number): $THROTTLE" >&2
+            exit 1
+        fi
+        # Shift one extra param
+        shift
+    fi
     if [ "$1" = "-d" ] || [ "$1" = "--depth" ]; then
         DEPTH="$2"
         echo "$DEPTH" | grep -E "^[0-9]+$" > /dev/null 2>&1
@@ -104,6 +131,7 @@ while [ -n "$1" ]; do
     shift
 done
 
+
 if [ -t 1 ] || [ "$FORCE_COLOR" -eq 1 ]; then
     # Our output is not being redirected, so we can use colors.
     C_RED="\033[1;31m"
@@ -112,7 +140,11 @@ if [ -t 1 ] || [ "$FORCE_COLOR" -eq 1 ]; then
     C_BLUE="\033[1;34m"
     C_PURPLE="\033[1;35m"
     C_CYAN="\033[1;36m"
-    C_RESET="$(tput sgr0)"
+    C_RESET="$(tput sgr0)" # Linux sgr0
+    if [ $(uname) = "FreeBSD" ]
+    then
+        C_RESET="$(tput reset)" # FreeBSD reset
+    fi
 fi
 
 C_OK="$C_GREEN"
@@ -123,8 +155,12 @@ C_NEEDS_COMMIT="$C_RED"
 C_NEEDS_UPSTREAM="$C_PURPLE"
 C_UNTRACKED="$C_CYAN"
 C_STASHES="$C_YELLOW"
+C_UNSAFE="$C_PURPLE"
 
-# Find all .git dirs, up to DEPTH levels deep. If DEPTH is 0, the scan in
+# Get current username so we can check .git dir ownership.
+ID="$(id -n -u)"
+
+# Find all .git dirs, up to DEPTH levels deep. If DEPTH is 0, the scan is
 # infinitely deep
 FIND_OPTS=""
 if [ "$DEPTH" -ne 0 ]; then
@@ -140,6 +176,15 @@ for DIR in "${@:-"."}"; do
         GIT_DIR="$PROJ_DIR/.git"
         GIT_CONF="$PROJ_DIR/.git/config"
         
+        # Check if the repo is safe (https://github.blog/2022-04-12-git-security-vulnerability-announced/)
+        if [ -d "$GIT_DIR" ]; then
+            GIT_DIR_OWNER="$(ls -ld "$GIT_DIR" | awk 'NR==1 {print $3}')"
+            if [ "$ID" != "$GIT_DIR_OWNER" ]; then
+                printf "${PROJ_DIR}: ${C_UNSAFE}Unsafe ownership, owned by someone else. Skipping.${C_RESET}\n"
+                continue
+            fi
+        fi
+
         # Check git config for this project to see if we should ignore this repo.
         IGNORE=$(git config -f "$GIT_CONF" --bool mgitstatus.ignore)
         if [ "$IGNORE" = "true" ]; then
@@ -167,22 +212,22 @@ for DIR in "${@:-"."}"; do
             git --work-tree "$(dirname "$GIT_DIR")" --git-dir "$GIT_DIR" fetch -q >/dev/null
         fi
 
-	LOCKFILE="${GIT_DIR}/index.lock"
-	if [ -f "${LOCKFILE}" ]
-	then
-		echo "ARK-ICT: huh?? ${LOCKFILE}"
-	fi
+        LOCKFILE="${GIT_DIR}/index.lock"
+
+        if [ -f "${LOCKFILE}" ]
+        then
+            echo "ARK-ICT: huh?? ${LOCKFILE}"
+        fi
         # Refresh the index, or we might get wrong results.
         git --work-tree "$(dirname "$GIT_DIR")" --git-dir "$GIT_DIR" update-index -q --refresh >/dev/null 2>&1
-	LOCKFILE="${GIT_DIR}/index.lock"
-	if [ -f "${LOCKFILE}" ]
-	then
-		if [ ${DEBUG} -eq 1 ]
-		then
-			echo "ARK-ICT: Bug detected that update-index does not remove lockfile ${LOCKFILE} : https://gitlab.com/tortoisegit/tortoisegit/-/issues/2233"
-		fi
-		rm "${LOCKFILE}"
-	fi
+        if [ -f "${LOCKFILE}" ]
+        then
+            if [ ${DEBUG} -eq 1 ]
+            then
+                echo "ARK-ICT: Bug detected that update-index does not remove lockfile ${LOCKFILE} : https://gitlab.com/tortoisegit/tortoisegit/-/issues/2233"
+            fi
+            rm "${LOCKFILE}"
+        fi
 
         # Find all remote branches that have been checked out and figure out if
         # they need a push or pull. We do this with various tests and put the name
@@ -253,35 +298,57 @@ for DIR in "${@:-"."}"; do
         STASHES=$(git stash list | wc -l)
         cd "$OLDPWD" || exit
 
-        # Build up the status string
+        # Build up the status string if not flattening. Otherwise, print
+        # results immediately.
         IS_OK=0  # 0 = Repo needs something, 1 = Repo needs nothing ('ok')
         STATUS_NEEDS=""
         if [ -n "$NEEDS_PUSH_BRANCHES" ] && [ "$NO_PUSH" -eq 0 ]; then
-            STATUS_NEEDS="${STATUS_NEEDS}${C_NEEDS_PUSH}Needs push ($NEEDS_PUSH_BRANCHES)${C_RESET} "
+            THIS_STATUS="${C_NEEDS_PUSH}Needs push ($NEEDS_PUSH_BRANCHES)${C_RESET}"
+            STATUS_NEEDS="${STATUS_NEEDS}${THIS_STATUS} "
+            [ "$FLATTEN" -eq 1 ] && printf "${PROJ_DIR}: $THIS_STATUS\n"
         fi
         if [ -n "$NEEDS_PULL_BRANCHES" ] && [ "$NO_PULL" -eq 0 ]; then
-            STATUS_NEEDS="${STATUS_NEEDS}${C_NEEDS_PULL}Needs pull ($NEEDS_PULL_BRANCHES)${C_RESET} "
+            THIS_STATUS="${C_NEEDS_PULL}Needs pull ($NEEDS_PULL_BRANCHES)${C_RESET}"
+            STATUS_NEEDS="${STATUS_NEEDS}${THIS_STATUS} "
+            [ "$FLATTEN" -eq 1 ] && printf "${PROJ_DIR}: $THIS_STATUS\n"
         fi
         if [ -n "$NEEDS_UPSTREAM_BRANCHES" ] && [ "$NO_UPSTREAM" -eq 0 ]; then
-            STATUS_NEEDS="${STATUS_NEEDS}${C_NEEDS_UPSTREAM}Needs upstream ($NEEDS_UPSTREAM_BRANCHES)${C_RESET} "
+            THIS_STATUS="${C_NEEDS_UPSTREAM}Needs upstream ($NEEDS_UPSTREAM_BRANCHES)${C_RESET}"
+            STATUS_NEEDS="${STATUS_NEEDS}${THIS_STATUS} "
+            [ "$FLATTEN" -eq 1 ] && printf "${PROJ_DIR}: $THIS_STATUS\n"
         fi
         if [ "$UNSTAGED" -ne 0 ] || [ "$UNCOMMITTED" -ne 0 ] && [ "$NO_UNCOMMITTED" -eq 0 ]; then
-            STATUS_NEEDS="${STATUS_NEEDS}${C_NEEDS_COMMIT}Uncommitted changes${C_RESET} "
+            THIS_STATUS="${C_NEEDS_COMMIT}Uncommitted changes${C_RESET}"
+            STATUS_NEEDS="${STATUS_NEEDS}${THIS_STATUS} "
+            [ "$FLATTEN" -eq 1 ] && printf "${PROJ_DIR}: $THIS_STATUS\n"
         fi
         if [ "$UNTRACKED" != "" ] && [ "$NO_UNTRACKED" -eq 0 ]; then
-            STATUS_NEEDS="${STATUS_NEEDS}${C_UNTRACKED}Untracked files${C_RESET} "
+            THIS_STATUS="${C_UNTRACKED}Untracked files${C_RESET}"
+            STATUS_NEEDS="${STATUS_NEEDS}${THIS_STATUS} "
+            [ "$FLATTEN" -eq 1 ] && printf "${PROJ_DIR}: $THIS_STATUS\n"
         fi
         if [ "$STASHES" -ne 0 ] && [ "$NO_STASHES" -eq 0 ]; then
-            STATUS_NEEDS="${STATUS_NEEDS}${C_STASHES}$STASHES stashes${C_RESET} "
+            THIS_STATUS="${C_STASHES}$STASHES stashes${C_RESET}"
+            STATUS_NEEDS="${STATUS_NEEDS}${THIS_STATUS} "
+            [ "$FLATTEN" -eq 1 ] && printf "${PROJ_DIR}: $THIS_STATUS\n"
         fi
         if [ "$STATUS_NEEDS" = "" ]; then
             IS_OK=1
-            STATUS_NEEDS="${STATUS_NEEDS}${C_OK}ok${C_RESET} "
+            THIS_STATUS="${C_OK}ok${C_RESET}"
+            STATUS_NEEDS="${STATUS_NEEDS}${THIS_STATUS} "
+            [ "$FLATTEN" -eq 1 ] && [ "$EXCLUDE_OK" -ne 1 ] && printf "${PROJ_DIR}: $THIS_STATUS\n"
         fi
 
-        # Print the output, unless repo is 'ok' and -e was specified
-        if [ "$IS_OK" -ne 1 ] || [ "$EXCLUDE_OK" -ne 1 ]; then
-            printf "${PROJ_DIR}: $STATUS_NEEDS\n"
+        if [ "$FLATTEN" -ne 1 ]; then
+            # Print the output, unless repo is 'ok' and -e was specified
+            if [ "$IS_OK" -ne 1 ] || [ "$EXCLUDE_OK" -ne 1 ]; then
+                printf "${PROJ_DIR}: $STATUS_NEEDS\n"
+            fi
+        fi
+
+        # Throttle if requested
+        if [ "$DO_FETCH" -eq 1 ] && [ "$THROTTLE" -ne 0 ]; then
+            sleep "$THROTTLE"
         fi
     done
 done
